// dsh-link: FRP (STCP) tunnel integration.
// Every node publishes its local HTTP port through an frps server (stcp provider) and
// reaches peers through local visitor ports, so no machine needs an inbound port.
import { spawn as nodeSpawn } from 'node:child_process';
import { closeSync, openSync } from 'node:fs';
import { promises as fs } from 'node:fs';
import net from 'node:net';
import os from 'node:os';
import path from 'node:path';
import { LinkError, badRequest, newId, randomToken } from './util.mjs';

const FRPC_CANDIDATES = () => {
  const env = process.env.DSHLINK_FRPC;
  const win = process.platform === 'win32';
  const names = win ? ['frpc.exe', 'frpc'] : ['frpc'];
  const projectVendor = new URL('../vendor/frp', import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1');
  const dirs = [
    path.join(projectVendor, win ? 'windows-amd64' : 'linux-amd64'),
    path.join(process.env.DSHLINK_HOME ?? '', 'frp'),
    path.join(os.homedir(), '.dshlink', 'frp'),
    path.join(os.homedir(), 'frp'),
    win ? 'C:\\frp' : '/usr/local/bin',
    win ? 'D:\\frp' : '/usr/bin',
    '/opt/frp'
  ].filter(Boolean);
  const out = [];
  if (env) out.push(env);
  for (const dir of dirs) for (const name of names) out.push(path.join(dir, name));
  return out;
};

export async function findFrpc(cfg) {
  const explicit = cfg?.tunnel?.frpcPath;
  if (explicit) {
    try { await fs.access(explicit); return explicit; } catch { return explicit; }
  }
  for (const candidate of FRPC_CANDIDATES()) {
    try { await fs.access(candidate); return candidate; } catch { /* keep looking */ }
  }
  return null;
}

export function allocateVisitorPort(cfg, { base, used } = {}) {
  const start = base ?? cfg.tunnel?.visitorPortBase ?? 19100;
  const taken = new Set(used ?? (cfg.peers ?? []).map((p) => p.stcp?.visitorPort).filter(Boolean));
  taken.add(cfg.port);
  let port = start;
  while (taken.has(port) || port > 65535) port += 1;
  return port;
}

export function visitorsFor(cfg) {
  return (cfg.peers ?? [])
    .filter((p) => p.stcp && p.stcp.serverName && p.stcp.visitorPort)
    .map((p) => ({
      peer: p.name,
      serverName: p.stcp.serverName,
      secretKey: p.stcp.secretKey,
      bindAddr: '127.0.0.1',
      bindPort: p.stcp.visitorPort,
      url: p.url ?? `http://127.0.0.1:${p.stcp.visitorPort}`
    }));
}

function tomlString(value) {
  return JSON.stringify(String(value ?? ''));
}

export function frpConfigToml(cfg) {
  const t = cfg.tunnel;
  if (!t?.serverAddr) throw badRequest('tunnel.serverAddr is not set — run: dshlink tunnel setup --server <frps host>');
  if (!cfg.stcp?.proxyName || !cfg.stcp?.secretKey) throw badRequest('this node has no STCP identity — run: dshlink tunnel setup (or re-run dshlink init)');
  const lines = [];
  lines.push('# frpc.toml — generated by dsh-link. Edit dshlink.config.json instead of this file.');
  lines.push(`# node: ${cfg.name}  generated: ${new Date().toISOString()}`);
  lines.push('');
  lines.push(`serverAddr = ${tomlString(t.serverAddr)}`);
  lines.push(`serverPort = ${t.serverPort}`);
  lines.push('');
  lines.push(`user = ${tomlString(t.user ?? 'dsh-link')}`);
  lines.push('loginFailExit = false');
  lines.push('');
  if (t.token) {
    lines.push('auth.method = "token"');
    lines.push(`auth.token = ${tomlString(t.token)}`);
    lines.push('auth.additionalScopes = ["HeartBeats", "NewWorkConns"]');
  } else {
    lines.push('# auth.token is unset (frps must accept anonymous clients)');
    lines.push('auth.method = "token"');
  }
  lines.push(`transport.tls.enable = ${t.tls === false ? 'false' : 'true'}`);
  lines.push('');
  lines.push('webServer.addr = "127.0.0.1"');
  lines.push(`webServer.port = ${t.adminPort ?? 7400}`);
  lines.push('webServer.pprofEnable = false');
  lines.push('');
  lines.push(`log.to = ${tomlString(path.join(t.logDir ?? path.join(cfg.dataDir, 'frp'), 'frpc.log'))}`);
  lines.push('log.level = "info"');
  lines.push('log.maxDays = 7');
  lines.push('');
  lines.push('# --- provider: publish this node\'s dsh-link HTTP API privately ---');
  lines.push('[[proxies]]');
  lines.push(`name = ${tomlString(cfg.stcp.proxyName)}`);
  lines.push('type = "stcp"');
  lines.push(`secretKey = ${tomlString(cfg.stcp.secretKey)}`);
  const allowUsers = [...new Set([t.user ?? 'dsh-link', 'dsh-link'])];
  lines.push(`allowUsers = [${allowUsers.map(tomlString).join(', ')}]`);
  lines.push('localIP = "127.0.0.1"');
  lines.push(`localPort = ${cfg.port}`);
  lines.push('transport.useEncryption = true');
  lines.push('transport.useCompression = false');
  const visitors = visitorsFor(cfg);
  if (visitors.length) {
    lines.push('');
    lines.push('# --- visitors: local ports that reach a peer through frps ---');
    for (const visitor of visitors) {
      lines.push('[[visitors]]');
      lines.push(`name = ${tomlString(`to-${visitor.peer}`)}`);
      lines.push('type = "stcp"');
      lines.push(`serverName = ${tomlString(visitor.serverName)}`);
      if (visitor.secretKey) lines.push(`secretKey = ${tomlString(visitor.secretKey)}`);
      lines.push(`bindAddr = "127.0.0.1"`);
      lines.push(`bindPort = ${visitor.bindPort}`);
      lines.push('transport.useEncryption = true');
      lines.push('transport.useCompression = false');
      lines.push('');
    }
  }
  return lines.join('\n');
}

export function parseFrpcTomlSummary(toml) {
  const text = String(toml ?? '');
  const pick = (key) => {
    const match = new RegExp(`^\\s*${key}\\s*=\\s*"?([^"\\n]+)"?\\s*$`, 'm').exec(text);
    return match ? match[1].trim() : null;
  };
  const sections = text.split(/^\s*\[\[/m).slice(1);
  const proxies = [];
  const visitors = [];
  for (const section of sections) {
    const [header, ...rest] = section.split('\n');
    const body = rest.join('\n');
    const entry = {
      kind: header.trim().replace(/\]\]$/, ''),
      name: (/^\s*name\s*=\s*"?([^"\n]+)"?/m.exec(body) ?? [])[1] ?? null,
      type: (/^\s*type\s*=\s*"?([^"\n]+)"?/m.exec(body) ?? [])[1] ?? null,
      localPort: (/^\s*localPort\s*=\s*(\d+)/m.exec(body) ?? [])[1] ?? null,
      serverName: (/^\s*serverName\s*=\s*"?([^"\n]+)"?/m.exec(body) ?? [])[1] ?? null,
      bindPort: (/^\s*bindPort\s*=\s*(\d+)/m.exec(body) ?? [])[1] ?? null,
      secretKey: (/^\s*secretKey\s*=\s*"?([^"\n]+)"?/m.exec(body) ?? [])[1] ?? null
    };
    if (entry.kind === 'proxies') proxies.push(entry);
    else if (entry.kind === 'visitors') visitors.push(entry);
  }
  return { serverAddr: pick('serverAddr'), serverPort: pick('serverPort'), user: pick('user'), proxies, visitors };
}

async function pidAlive(pid) {
  if (!pid) return false;
  try {
    process.kill(pid, 0);
    return true;
  } catch (err) {
    return err.code === 'EPERM';
  }
}

async function portListening(host, port, timeoutMs = 700) {
  return new Promise((resolve) => {
    const socket = net.connect({ host, port });
    const done = (result) => { socket.destroy(); resolve(result); };
    socket.setTimeout(timeoutMs, () => done(false));
    socket.once('connect', () => done(true));
    socket.once('error', () => done(false));
  });
}

export class TunnelManager {
  constructor(cfg, { log = console, spawnImpl = nodeSpawn } = {}) {
    this.cfg = cfg;
    this.log = log;
    this.spawn = spawnImpl;
    this.dir = cfg.tunnel?.logDir ?? path.join(cfg.dataDir, 'frp');
    this.configPath = path.join(this.dir, 'frpc.toml');
    this.pidPath = path.join(this.dir, 'frpc.pid');
    this.logPath = path.join(this.dir, 'frpc.log');
  }

  async writeConfig() {
    const toml = frpConfigToml(this.cfg);
    await fs.mkdir(this.dir, { recursive: true });
    await fs.writeFile(this.configPath, toml, 'utf8');
    // Keep a copy of the connection secret out of the repo but readable for the operator.
    return { path: this.configPath, toml };
  }

  async readPid() {
    try {
      const raw = (await fs.readFile(this.pidPath, 'utf8')).trim();
      const pid = Number.parseInt(raw, 10);
      return Number.isFinite(pid) ? pid : null;
    } catch {
      return null;
    }
  }

  async status() {
    const pid = await this.readPid();
    const running = await pidAlive(pid);
    let logTail = null;
    try {
      const text = await fs.readFile(this.logPath, 'utf8');
      logTail = text.split('\n').slice(-12).join('\n');
    } catch { /* no log yet */ }
    const visitors = visitorsFor(this.cfg);
    return {
      enabled: !!this.cfg.tunnel?.enabled,
      serverAddr: this.cfg.tunnel?.serverAddr ?? null,
      serverPort: this.cfg.tunnel?.serverPort ?? null,
      frpcPath: await findFrpc(this.cfg),
      configPath: this.configPath,
      running,
      pid: running ? pid : null,
      reason: running ? null : (pid ? `pid ${pid} is not alive` : 'not started'),
      visitors,
      visitorPortsListening: await Promise.all(visitors.map(async (v) => ({ peer: v.peer, port: v.bindPort, listening: await portListening(v.bindAddr, v.bindPort) }))),
      logTail
    };
  }

  async waitForAdminPortFree(timeoutMs = 6000) {
    const port = this.cfg.tunnel?.adminPort ?? 7400;
    const deadline = Date.now() + timeoutMs;
    while (Date.now() < deadline) {
      if (!(await portListening('127.0.0.1', port, 300))) return true;
      await new Promise((resolve) => setTimeout(resolve, 150));
    }
    return false;
  }

  async adminPortAvailable(port) {
    return new Promise((resolve) => {
      const server = net.createServer();
      server.once('error', () => resolve(false));
      server.listen(port, '127.0.0.1', () => server.close(() => resolve(true)));
    });
  }

  /**
   * frpc's admin port must be free *on this machine*. Two nodes on one host (or a
   * mirrored WSL distro) can collide, so pick the next free port when that happens.
   */
  async ensureAdminPort() {
    const base = this.cfg.tunnel?.adminPort ?? 7400;
    if (await this.adminPortAvailable(base)) return base;
    for (let port = base + 1; port < Math.min(base + 250, 65535); port += 1) {
      if (await this.adminPortAvailable(port)) {
        this.cfg.tunnel.adminPort = port;
        this.log.warn?.( `dsh-link tunnel: admin port ${base} is taken; using ${port}`);
        return port;
      }
    }
    throw new LinkError(3, 'no_admin_port', `no free frpc admin port near ${base}`);
  }

  /**
   * STCP visitor ports are bound on *this* machine. When another node (or a mirrored
   * WSL distro) already holds one, move it to the next free port and mark the config dirty.
   */
  async ensureVisitorPorts() {
    const reassigned = [];
    for (const peer of this.cfg.peers ?? []) {
      const current = peer.stcp?.visitorPort;
      if (!current) continue;
      if (await this.adminPortAvailable(current)) continue;
      let port = current + 1;
      while (port < 65535 && !(await this.adminPortAvailable(port))) port += 1;
      if (port >= 65535) throw new LinkError(3, 'no_visitor_port', `no free visitor port for ${peer.name} near ${current}`);
      peer.stcp.visitorPort = port;
      peer.url = `http://127.0.0.1:${port}`;
      reassigned.push({ peer: peer.name, from: current, to: port });
      this.log.warn?.( `dsh-link tunnel: visitor port ${current} is taken; ${peer.name} now uses ${port}`);
    }
    if (reassigned.length) this.dirty = true;
    return reassigned;
  }

  async tailLog(lines = 6) {
    try {
      const text = await fs.readFile(this.logPath, 'utf8');
      return text.trimEnd().split('\n').slice(-lines).join('\n');
    } catch {
      return '(no log)';
    }
  }

  async start() {
    if (!this.cfg.tunnel?.enabled) throw badRequest('the tunnel is disabled (dshlink tunnel enable)');
    const existing = await this.readPid();
    if (await pidAlive(existing)) return { running: true, pid: existing, configPath: this.configPath, reused: true, visitors: visitorsFor(this.cfg) };
    const frpc = await findFrpc(this.cfg);
    if (!frpc) throw new LinkError(3, 'frpc_missing', 'frpc binary not found; pass --frpc <path> to tunnel setup or set DSHLINK_FRPC');
    // Pick bindable ports *before* writing the config that embeds them.
    const reassigned = await this.ensureVisitorPorts();
    await this.ensureAdminPort();
    const { path: configPath } = await this.writeConfig();
    await fs.mkdir(this.dir, { recursive: true });
    // A previous frpc must have released its admin port first, otherwise the new
    // instance exits on startup and the tunnels silently stay down.
    await this.waitForAdminPortFree();
    const fd = openSync(this.logPath, 'a');
    let child;
    try {
      child = this.spawn(frpc, ['-c', configPath], { detached: true, stdio: ['ignore', fd, fd], windowsHide: true });
    } finally {
      closeSync(fd);
    }
    child.unref?.();
    await fs.writeFile(this.pidPath, String(child.pid) + '\n', 'utf8');
    await new Promise((resolve) => setTimeout(resolve, 600));
    if (!(await pidAlive(child.pid))) {
      const tail = await this.tailLog();
      await fs.rm(this.pidPath, { force: true });
      throw new LinkError(3, 'frpc_failed', `frpc exited immediately — check ${this.logPath}\n${tail}`);
    }
    this.log.info?.( `dsh-link tunnel: frpc started (pid ${child.pid}) with ${configPath}`);
    return { running: true, pid: child.pid, configPath, frpcPath: frpc, visitors: visitorsFor(this.cfg), started: true, reassigned, dirty: !!this.dirty };
  }

  async stop() {
    const pid = await this.readPid();
    if (!(await pidAlive(pid))) {
      await fs.rm(this.pidPath, { force: true });
      return { stopped: false, reason: 'not running' };
    }
    try {
      process.kill(pid);
    } catch (err) {
      return { stopped: false, reason: err.message };
    }
    for (let i = 0; i < 30; i += 1) {
      if (!(await pidAlive(pid))) break;
      await new Promise((resolve) => setTimeout(resolve, 100));
    }
    await this.waitForAdminPortFree();
    await fs.rm(this.pidPath, { force: true });
    return { stopped: true, pid };
  }

  async relaunch({ force = false } = {}) {
    await this.stop();
    if (!this.cfg.tunnel?.enabled) return { running: false, reason: 'tunnel disabled', configPath: this.configPath, visitors: visitorsFor(this.cfg) };
    try {
      return await this.start();
    } catch (err) {
      if (force) throw err;
      return { running: false, reason: err.message, configPath: this.configPath, visitors: visitorsFor(this.cfg) };
    }
  }

  share() {
    if (!this.cfg.stcp?.secretKey) {
      this.cfg.stcp = { ...(this.cfg.stcp ?? {}), proxyName: `dshlink-${this.cfg.name}`, secretKey: randomToken(24) };
    }
    return {
      node: this.cfg.name,
      proxyName: this.cfg.stcp.proxyName,
      secretKey: this.cfg.stcp.secretKey,
      serverAddr: this.cfg.tunnel?.serverAddr ?? null,
      serverPort: this.cfg.tunnel?.serverPort ?? 7000,
      user: this.cfg.tunnel?.user ?? 'dsh-link',
      shareId: newId('share')
    };
  }
}
